// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/proto/requestReply.proto
// Protobuf Java Version: 4.27.3

package pt.uminho.di.a3m.sockets.request_reply;

final class RequestReply {
  private RequestReply() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 3,
      /* suffix= */ "",
      RequestReply.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RRMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pt.uminho.di.a3m.sockets.request_reply.RRMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .pt.uminho.di.a3m.sockets.request_reply.RoutingId routingIds = 1;</code>
     */
    java.util.List<pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId> 
        getRoutingIdsList();
    /**
     * <code>repeated .pt.uminho.di.a3m.sockets.request_reply.RoutingId routingIds = 1;</code>
     */
    pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId getRoutingIds(int index);
    /**
     * <code>repeated .pt.uminho.di.a3m.sockets.request_reply.RoutingId routingIds = 1;</code>
     */
    int getRoutingIdsCount();
    /**
     * <code>repeated .pt.uminho.di.a3m.sockets.request_reply.RoutingId routingIds = 1;</code>
     */
    java.util.List<? extends pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingIdOrBuilder> 
        getRoutingIdsOrBuilderList();
    /**
     * <code>repeated .pt.uminho.di.a3m.sockets.request_reply.RoutingId routingIds = 1;</code>
     */
    pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingIdOrBuilder getRoutingIdsOrBuilder(
        int index);

    /**
     * <code>bytes payload = 2;</code>
     * @return The payload.
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * Protobuf type {@code pt.uminho.di.a3m.sockets.request_reply.RRMsg}
   */
  public static final class RRMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pt.uminho.di.a3m.sockets.request_reply.RRMsg)
      RRMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 3,
        /* suffix= */ "",
        RRMsg.class.getName());
    }
    // Use RRMsg.newBuilder() to construct.
    private RRMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private RRMsg() {
      routingIds_ = java.util.Collections.emptyList();
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pt.uminho.di.a3m.sockets.request_reply.RequestReply.internal_static_pt_uminho_di_a3m_sockets_request_reply_RRMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pt.uminho.di.a3m.sockets.request_reply.RequestReply.internal_static_pt_uminho_di_a3m_sockets_request_reply_RRMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg.class, pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg.Builder.class);
    }

    public static final int ROUTINGIDS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId> routingIds_;
    /**
     * <code>repeated .pt.uminho.di.a3m.sockets.request_reply.RoutingId routingIds = 1;</code>
     */
    @java.lang.Override
    public java.util.List<pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId> getRoutingIdsList() {
      return routingIds_;
    }
    /**
     * <code>repeated .pt.uminho.di.a3m.sockets.request_reply.RoutingId routingIds = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingIdOrBuilder> 
        getRoutingIdsOrBuilderList() {
      return routingIds_;
    }
    /**
     * <code>repeated .pt.uminho.di.a3m.sockets.request_reply.RoutingId routingIds = 1;</code>
     */
    @java.lang.Override
    public int getRoutingIdsCount() {
      return routingIds_.size();
    }
    /**
     * <code>repeated .pt.uminho.di.a3m.sockets.request_reply.RoutingId routingIds = 1;</code>
     */
    @java.lang.Override
    public pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId getRoutingIds(int index) {
      return routingIds_.get(index);
    }
    /**
     * <code>repeated .pt.uminho.di.a3m.sockets.request_reply.RoutingId routingIds = 1;</code>
     */
    @java.lang.Override
    public pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingIdOrBuilder getRoutingIdsOrBuilder(
        int index) {
      return routingIds_.get(index);
    }

    public static final int PAYLOAD_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes payload = 2;</code>
     * @return The payload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < routingIds_.size(); i++) {
        output.writeMessage(1, routingIds_.get(i));
      }
      if (!payload_.isEmpty()) {
        output.writeBytes(2, payload_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < routingIds_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, routingIds_.get(i));
      }
      if (!payload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, payload_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg)) {
        return super.equals(obj);
      }
      pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg other = (pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg) obj;

      if (!getRoutingIdsList()
          .equals(other.getRoutingIdsList())) return false;
      if (!getPayload()
          .equals(other.getPayload())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRoutingIdsCount() > 0) {
        hash = (37 * hash) + ROUTINGIDS_FIELD_NUMBER;
        hash = (53 * hash) + getRoutingIdsList().hashCode();
      }
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pt.uminho.di.a3m.sockets.request_reply.RRMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pt.uminho.di.a3m.sockets.request_reply.RRMsg)
        pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pt.uminho.di.a3m.sockets.request_reply.RequestReply.internal_static_pt_uminho_di_a3m_sockets_request_reply_RRMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pt.uminho.di.a3m.sockets.request_reply.RequestReply.internal_static_pt_uminho_di_a3m_sockets_request_reply_RRMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg.class, pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg.Builder.class);
      }

      // Construct using pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (routingIdsBuilder_ == null) {
          routingIds_ = java.util.Collections.emptyList();
        } else {
          routingIds_ = null;
          routingIdsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        payload_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pt.uminho.di.a3m.sockets.request_reply.RequestReply.internal_static_pt_uminho_di_a3m_sockets_request_reply_RRMsg_descriptor;
      }

      @java.lang.Override
      public pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg getDefaultInstanceForType() {
        return pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg.getDefaultInstance();
      }

      @java.lang.Override
      public pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg build() {
        pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg buildPartial() {
        pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg result = new pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg result) {
        if (routingIdsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            routingIds_ = java.util.Collections.unmodifiableList(routingIds_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.routingIds_ = routingIds_;
        } else {
          result.routingIds_ = routingIdsBuilder_.build();
        }
      }

      private void buildPartial0(pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.payload_ = payload_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg) {
          return mergeFrom((pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg other) {
        if (other == pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg.getDefaultInstance()) return this;
        if (routingIdsBuilder_ == null) {
          if (!other.routingIds_.isEmpty()) {
            if (routingIds_.isEmpty()) {
              routingIds_ = other.routingIds_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRoutingIdsIsMutable();
              routingIds_.addAll(other.routingIds_);
            }
            onChanged();
          }
        } else {
          if (!other.routingIds_.isEmpty()) {
            if (routingIdsBuilder_.isEmpty()) {
              routingIdsBuilder_.dispose();
              routingIdsBuilder_ = null;
              routingIds_ = other.routingIds_;
              bitField0_ = (bitField0_ & ~0x00000001);
              routingIdsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRoutingIdsFieldBuilder() : null;
            } else {
              routingIdsBuilder_.addAllMessages(other.routingIds_);
            }
          }
        }
        if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId m =
                    input.readMessage(
                        pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId.parser(),
                        extensionRegistry);
                if (routingIdsBuilder_ == null) {
                  ensureRoutingIdsIsMutable();
                  routingIds_.add(m);
                } else {
                  routingIdsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              case 18: {
                payload_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId> routingIds_ =
        java.util.Collections.emptyList();
      private void ensureRoutingIdsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          routingIds_ = new java.util.ArrayList<pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId>(routingIds_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId, pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId.Builder, pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingIdOrBuilder> routingIdsBuilder_;

      /**
       * <code>repeated .pt.uminho.di.a3m.sockets.request_reply.RoutingId routingIds = 1;</code>
       */
      public java.util.List<pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId> getRoutingIdsList() {
        if (routingIdsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(routingIds_);
        } else {
          return routingIdsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .pt.uminho.di.a3m.sockets.request_reply.RoutingId routingIds = 1;</code>
       */
      public int getRoutingIdsCount() {
        if (routingIdsBuilder_ == null) {
          return routingIds_.size();
        } else {
          return routingIdsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .pt.uminho.di.a3m.sockets.request_reply.RoutingId routingIds = 1;</code>
       */
      public pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId getRoutingIds(int index) {
        if (routingIdsBuilder_ == null) {
          return routingIds_.get(index);
        } else {
          return routingIdsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .pt.uminho.di.a3m.sockets.request_reply.RoutingId routingIds = 1;</code>
       */
      public Builder setRoutingIds(
          int index, pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId value) {
        if (routingIdsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoutingIdsIsMutable();
          routingIds_.set(index, value);
          onChanged();
        } else {
          routingIdsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pt.uminho.di.a3m.sockets.request_reply.RoutingId routingIds = 1;</code>
       */
      public Builder setRoutingIds(
          int index, pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId.Builder builderForValue) {
        if (routingIdsBuilder_ == null) {
          ensureRoutingIdsIsMutable();
          routingIds_.set(index, builderForValue.build());
          onChanged();
        } else {
          routingIdsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pt.uminho.di.a3m.sockets.request_reply.RoutingId routingIds = 1;</code>
       */
      public Builder addRoutingIds(pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId value) {
        if (routingIdsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoutingIdsIsMutable();
          routingIds_.add(value);
          onChanged();
        } else {
          routingIdsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .pt.uminho.di.a3m.sockets.request_reply.RoutingId routingIds = 1;</code>
       */
      public Builder addRoutingIds(
          int index, pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId value) {
        if (routingIdsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoutingIdsIsMutable();
          routingIds_.add(index, value);
          onChanged();
        } else {
          routingIdsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pt.uminho.di.a3m.sockets.request_reply.RoutingId routingIds = 1;</code>
       */
      public Builder addRoutingIds(
          pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId.Builder builderForValue) {
        if (routingIdsBuilder_ == null) {
          ensureRoutingIdsIsMutable();
          routingIds_.add(builderForValue.build());
          onChanged();
        } else {
          routingIdsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pt.uminho.di.a3m.sockets.request_reply.RoutingId routingIds = 1;</code>
       */
      public Builder addRoutingIds(
          int index, pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId.Builder builderForValue) {
        if (routingIdsBuilder_ == null) {
          ensureRoutingIdsIsMutable();
          routingIds_.add(index, builderForValue.build());
          onChanged();
        } else {
          routingIdsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pt.uminho.di.a3m.sockets.request_reply.RoutingId routingIds = 1;</code>
       */
      public Builder addAllRoutingIds(
          java.lang.Iterable<? extends pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId> values) {
        if (routingIdsBuilder_ == null) {
          ensureRoutingIdsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, routingIds_);
          onChanged();
        } else {
          routingIdsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .pt.uminho.di.a3m.sockets.request_reply.RoutingId routingIds = 1;</code>
       */
      public Builder clearRoutingIds() {
        if (routingIdsBuilder_ == null) {
          routingIds_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          routingIdsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .pt.uminho.di.a3m.sockets.request_reply.RoutingId routingIds = 1;</code>
       */
      public Builder removeRoutingIds(int index) {
        if (routingIdsBuilder_ == null) {
          ensureRoutingIdsIsMutable();
          routingIds_.remove(index);
          onChanged();
        } else {
          routingIdsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .pt.uminho.di.a3m.sockets.request_reply.RoutingId routingIds = 1;</code>
       */
      public pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId.Builder getRoutingIdsBuilder(
          int index) {
        return getRoutingIdsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .pt.uminho.di.a3m.sockets.request_reply.RoutingId routingIds = 1;</code>
       */
      public pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingIdOrBuilder getRoutingIdsOrBuilder(
          int index) {
        if (routingIdsBuilder_ == null) {
          return routingIds_.get(index);  } else {
          return routingIdsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .pt.uminho.di.a3m.sockets.request_reply.RoutingId routingIds = 1;</code>
       */
      public java.util.List<? extends pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingIdOrBuilder> 
           getRoutingIdsOrBuilderList() {
        if (routingIdsBuilder_ != null) {
          return routingIdsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(routingIds_);
        }
      }
      /**
       * <code>repeated .pt.uminho.di.a3m.sockets.request_reply.RoutingId routingIds = 1;</code>
       */
      public pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId.Builder addRoutingIdsBuilder() {
        return getRoutingIdsFieldBuilder().addBuilder(
            pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId.getDefaultInstance());
      }
      /**
       * <code>repeated .pt.uminho.di.a3m.sockets.request_reply.RoutingId routingIds = 1;</code>
       */
      public pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId.Builder addRoutingIdsBuilder(
          int index) {
        return getRoutingIdsFieldBuilder().addBuilder(
            index, pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId.getDefaultInstance());
      }
      /**
       * <code>repeated .pt.uminho.di.a3m.sockets.request_reply.RoutingId routingIds = 1;</code>
       */
      public java.util.List<pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId.Builder> 
           getRoutingIdsBuilderList() {
        return getRoutingIdsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId, pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId.Builder, pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingIdOrBuilder> 
          getRoutingIdsFieldBuilder() {
        if (routingIdsBuilder_ == null) {
          routingIdsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId, pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId.Builder, pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingIdOrBuilder>(
                  routingIds_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          routingIds_ = null;
        }
        return routingIdsBuilder_;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes payload = 2;</code>
       * @return The payload.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <code>bytes payload = 2;</code>
       * @param value The payload to set.
       * @return This builder for chaining.
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        payload_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bytes payload = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPayload() {
        bitField0_ = (bitField0_ & ~0x00000002);
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pt.uminho.di.a3m.sockets.request_reply.RRMsg)
    }

    // @@protoc_insertion_point(class_scope:pt.uminho.di.a3m.sockets.request_reply.RRMsg)
    private static final pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg();
    }

    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RRMsg>
        PARSER = new com.google.protobuf.AbstractParser<RRMsg>() {
      @java.lang.Override
      public RRMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RRMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RRMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pt.uminho.di.a3m.sockets.request_reply.RequestReply.RRMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RoutingIdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pt.uminho.di.a3m.sockets.request_reply.RoutingId)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * clock identifier (integer)
     * </pre>
     *
     * <code>int32 intIdentifier = 1;</code>
     * @return Whether the intIdentifier field is set.
     */
    boolean hasIntIdentifier();
    /**
     * <pre>
     * clock identifier (integer)
     * </pre>
     *
     * <code>int32 intIdentifier = 1;</code>
     * @return The intIdentifier.
     */
    int getIntIdentifier();

    /**
     * <pre>
     * socket identifier
     * </pre>
     *
     * <code>.pt.uminho.di.a3m.sockets.request_reply.SocketIdentifier socketIdentifier = 2;</code>
     * @return Whether the socketIdentifier field is set.
     */
    boolean hasSocketIdentifier();
    /**
     * <pre>
     * socket identifier
     * </pre>
     *
     * <code>.pt.uminho.di.a3m.sockets.request_reply.SocketIdentifier socketIdentifier = 2;</code>
     * @return The socketIdentifier.
     */
    pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier getSocketIdentifier();
    /**
     * <pre>
     * socket identifier
     * </pre>
     *
     * <code>.pt.uminho.di.a3m.sockets.request_reply.SocketIdentifier socketIdentifier = 2;</code>
     */
    pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifierOrBuilder getSocketIdentifierOrBuilder();

    pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId.RoutingIdCase getRoutingIdCase();
  }
  /**
   * Protobuf type {@code pt.uminho.di.a3m.sockets.request_reply.RoutingId}
   */
  public static final class RoutingId extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pt.uminho.di.a3m.sockets.request_reply.RoutingId)
      RoutingIdOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 3,
        /* suffix= */ "",
        RoutingId.class.getName());
    }
    // Use RoutingId.newBuilder() to construct.
    private RoutingId(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private RoutingId() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pt.uminho.di.a3m.sockets.request_reply.RequestReply.internal_static_pt_uminho_di_a3m_sockets_request_reply_RoutingId_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pt.uminho.di.a3m.sockets.request_reply.RequestReply.internal_static_pt_uminho_di_a3m_sockets_request_reply_RoutingId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId.class, pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId.Builder.class);
    }

    private int routingIdCase_ = 0;
    @SuppressWarnings("serial")
    private java.lang.Object routingId_;
    public enum RoutingIdCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      INTIDENTIFIER(1),
      SOCKETIDENTIFIER(2),
      ROUTINGID_NOT_SET(0);
      private final int value;
      private RoutingIdCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static RoutingIdCase valueOf(int value) {
        return forNumber(value);
      }

      public static RoutingIdCase forNumber(int value) {
        switch (value) {
          case 1: return INTIDENTIFIER;
          case 2: return SOCKETIDENTIFIER;
          case 0: return ROUTINGID_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public RoutingIdCase
    getRoutingIdCase() {
      return RoutingIdCase.forNumber(
          routingIdCase_);
    }

    public static final int INTIDENTIFIER_FIELD_NUMBER = 1;
    /**
     * <pre>
     * clock identifier (integer)
     * </pre>
     *
     * <code>int32 intIdentifier = 1;</code>
     * @return Whether the intIdentifier field is set.
     */
    @java.lang.Override
    public boolean hasIntIdentifier() {
      return routingIdCase_ == 1;
    }
    /**
     * <pre>
     * clock identifier (integer)
     * </pre>
     *
     * <code>int32 intIdentifier = 1;</code>
     * @return The intIdentifier.
     */
    @java.lang.Override
    public int getIntIdentifier() {
      if (routingIdCase_ == 1) {
        return (java.lang.Integer) routingId_;
      }
      return 0;
    }

    public static final int SOCKETIDENTIFIER_FIELD_NUMBER = 2;
    /**
     * <pre>
     * socket identifier
     * </pre>
     *
     * <code>.pt.uminho.di.a3m.sockets.request_reply.SocketIdentifier socketIdentifier = 2;</code>
     * @return Whether the socketIdentifier field is set.
     */
    @java.lang.Override
    public boolean hasSocketIdentifier() {
      return routingIdCase_ == 2;
    }
    /**
     * <pre>
     * socket identifier
     * </pre>
     *
     * <code>.pt.uminho.di.a3m.sockets.request_reply.SocketIdentifier socketIdentifier = 2;</code>
     * @return The socketIdentifier.
     */
    @java.lang.Override
    public pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier getSocketIdentifier() {
      if (routingIdCase_ == 2) {
         return (pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier) routingId_;
      }
      return pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier.getDefaultInstance();
    }
    /**
     * <pre>
     * socket identifier
     * </pre>
     *
     * <code>.pt.uminho.di.a3m.sockets.request_reply.SocketIdentifier socketIdentifier = 2;</code>
     */
    @java.lang.Override
    public pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifierOrBuilder getSocketIdentifierOrBuilder() {
      if (routingIdCase_ == 2) {
         return (pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier) routingId_;
      }
      return pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (routingIdCase_ == 1) {
        output.writeInt32(
            1, (int)((java.lang.Integer) routingId_));
      }
      if (routingIdCase_ == 2) {
        output.writeMessage(2, (pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier) routingId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (routingIdCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(
              1, (int)((java.lang.Integer) routingId_));
      }
      if (routingIdCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier) routingId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId)) {
        return super.equals(obj);
      }
      pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId other = (pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId) obj;

      if (!getRoutingIdCase().equals(other.getRoutingIdCase())) return false;
      switch (routingIdCase_) {
        case 1:
          if (getIntIdentifier()
              != other.getIntIdentifier()) return false;
          break;
        case 2:
          if (!getSocketIdentifier()
              .equals(other.getSocketIdentifier())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (routingIdCase_) {
        case 1:
          hash = (37 * hash) + INTIDENTIFIER_FIELD_NUMBER;
          hash = (53 * hash) + getIntIdentifier();
          break;
        case 2:
          hash = (37 * hash) + SOCKETIDENTIFIER_FIELD_NUMBER;
          hash = (53 * hash) + getSocketIdentifier().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pt.uminho.di.a3m.sockets.request_reply.RoutingId}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pt.uminho.di.a3m.sockets.request_reply.RoutingId)
        pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingIdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pt.uminho.di.a3m.sockets.request_reply.RequestReply.internal_static_pt_uminho_di_a3m_sockets_request_reply_RoutingId_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pt.uminho.di.a3m.sockets.request_reply.RequestReply.internal_static_pt_uminho_di_a3m_sockets_request_reply_RoutingId_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId.class, pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId.Builder.class);
      }

      // Construct using pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (socketIdentifierBuilder_ != null) {
          socketIdentifierBuilder_.clear();
        }
        routingIdCase_ = 0;
        routingId_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pt.uminho.di.a3m.sockets.request_reply.RequestReply.internal_static_pt_uminho_di_a3m_sockets_request_reply_RoutingId_descriptor;
      }

      @java.lang.Override
      public pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId getDefaultInstanceForType() {
        return pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId.getDefaultInstance();
      }

      @java.lang.Override
      public pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId build() {
        pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId buildPartial() {
        pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId result = new pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId result) {
        int from_bitField0_ = bitField0_;
      }

      private void buildPartialOneofs(pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId result) {
        result.routingIdCase_ = routingIdCase_;
        result.routingId_ = this.routingId_;
        if (routingIdCase_ == 2 &&
            socketIdentifierBuilder_ != null) {
          result.routingId_ = socketIdentifierBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId) {
          return mergeFrom((pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId other) {
        if (other == pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId.getDefaultInstance()) return this;
        switch (other.getRoutingIdCase()) {
          case INTIDENTIFIER: {
            setIntIdentifier(other.getIntIdentifier());
            break;
          }
          case SOCKETIDENTIFIER: {
            mergeSocketIdentifier(other.getSocketIdentifier());
            break;
          }
          case ROUTINGID_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                routingId_ = input.readInt32();
                routingIdCase_ = 1;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getSocketIdentifierFieldBuilder().getBuilder(),
                    extensionRegistry);
                routingIdCase_ = 2;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int routingIdCase_ = 0;
      private java.lang.Object routingId_;
      public RoutingIdCase
          getRoutingIdCase() {
        return RoutingIdCase.forNumber(
            routingIdCase_);
      }

      public Builder clearRoutingId() {
        routingIdCase_ = 0;
        routingId_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      /**
       * <pre>
       * clock identifier (integer)
       * </pre>
       *
       * <code>int32 intIdentifier = 1;</code>
       * @return Whether the intIdentifier field is set.
       */
      public boolean hasIntIdentifier() {
        return routingIdCase_ == 1;
      }
      /**
       * <pre>
       * clock identifier (integer)
       * </pre>
       *
       * <code>int32 intIdentifier = 1;</code>
       * @return The intIdentifier.
       */
      public int getIntIdentifier() {
        if (routingIdCase_ == 1) {
          return (java.lang.Integer) routingId_;
        }
        return 0;
      }
      /**
       * <pre>
       * clock identifier (integer)
       * </pre>
       *
       * <code>int32 intIdentifier = 1;</code>
       * @param value The intIdentifier to set.
       * @return This builder for chaining.
       */
      public Builder setIntIdentifier(int value) {

        routingIdCase_ = 1;
        routingId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * clock identifier (integer)
       * </pre>
       *
       * <code>int32 intIdentifier = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIntIdentifier() {
        if (routingIdCase_ == 1) {
          routingIdCase_ = 0;
          routingId_ = null;
          onChanged();
        }
        return this;
      }

      private com.google.protobuf.SingleFieldBuilder<
          pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier, pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier.Builder, pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifierOrBuilder> socketIdentifierBuilder_;
      /**
       * <pre>
       * socket identifier
       * </pre>
       *
       * <code>.pt.uminho.di.a3m.sockets.request_reply.SocketIdentifier socketIdentifier = 2;</code>
       * @return Whether the socketIdentifier field is set.
       */
      @java.lang.Override
      public boolean hasSocketIdentifier() {
        return routingIdCase_ == 2;
      }
      /**
       * <pre>
       * socket identifier
       * </pre>
       *
       * <code>.pt.uminho.di.a3m.sockets.request_reply.SocketIdentifier socketIdentifier = 2;</code>
       * @return The socketIdentifier.
       */
      @java.lang.Override
      public pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier getSocketIdentifier() {
        if (socketIdentifierBuilder_ == null) {
          if (routingIdCase_ == 2) {
            return (pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier) routingId_;
          }
          return pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier.getDefaultInstance();
        } else {
          if (routingIdCase_ == 2) {
            return socketIdentifierBuilder_.getMessage();
          }
          return pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * socket identifier
       * </pre>
       *
       * <code>.pt.uminho.di.a3m.sockets.request_reply.SocketIdentifier socketIdentifier = 2;</code>
       */
      public Builder setSocketIdentifier(pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier value) {
        if (socketIdentifierBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          routingId_ = value;
          onChanged();
        } else {
          socketIdentifierBuilder_.setMessage(value);
        }
        routingIdCase_ = 2;
        return this;
      }
      /**
       * <pre>
       * socket identifier
       * </pre>
       *
       * <code>.pt.uminho.di.a3m.sockets.request_reply.SocketIdentifier socketIdentifier = 2;</code>
       */
      public Builder setSocketIdentifier(
          pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier.Builder builderForValue) {
        if (socketIdentifierBuilder_ == null) {
          routingId_ = builderForValue.build();
          onChanged();
        } else {
          socketIdentifierBuilder_.setMessage(builderForValue.build());
        }
        routingIdCase_ = 2;
        return this;
      }
      /**
       * <pre>
       * socket identifier
       * </pre>
       *
       * <code>.pt.uminho.di.a3m.sockets.request_reply.SocketIdentifier socketIdentifier = 2;</code>
       */
      public Builder mergeSocketIdentifier(pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier value) {
        if (socketIdentifierBuilder_ == null) {
          if (routingIdCase_ == 2 &&
              routingId_ != pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier.getDefaultInstance()) {
            routingId_ = pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier.newBuilder((pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier) routingId_)
                .mergeFrom(value).buildPartial();
          } else {
            routingId_ = value;
          }
          onChanged();
        } else {
          if (routingIdCase_ == 2) {
            socketIdentifierBuilder_.mergeFrom(value);
          } else {
            socketIdentifierBuilder_.setMessage(value);
          }
        }
        routingIdCase_ = 2;
        return this;
      }
      /**
       * <pre>
       * socket identifier
       * </pre>
       *
       * <code>.pt.uminho.di.a3m.sockets.request_reply.SocketIdentifier socketIdentifier = 2;</code>
       */
      public Builder clearSocketIdentifier() {
        if (socketIdentifierBuilder_ == null) {
          if (routingIdCase_ == 2) {
            routingIdCase_ = 0;
            routingId_ = null;
            onChanged();
          }
        } else {
          if (routingIdCase_ == 2) {
            routingIdCase_ = 0;
            routingId_ = null;
          }
          socketIdentifierBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * socket identifier
       * </pre>
       *
       * <code>.pt.uminho.di.a3m.sockets.request_reply.SocketIdentifier socketIdentifier = 2;</code>
       */
      public pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier.Builder getSocketIdentifierBuilder() {
        return getSocketIdentifierFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * socket identifier
       * </pre>
       *
       * <code>.pt.uminho.di.a3m.sockets.request_reply.SocketIdentifier socketIdentifier = 2;</code>
       */
      @java.lang.Override
      public pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifierOrBuilder getSocketIdentifierOrBuilder() {
        if ((routingIdCase_ == 2) && (socketIdentifierBuilder_ != null)) {
          return socketIdentifierBuilder_.getMessageOrBuilder();
        } else {
          if (routingIdCase_ == 2) {
            return (pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier) routingId_;
          }
          return pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * socket identifier
       * </pre>
       *
       * <code>.pt.uminho.di.a3m.sockets.request_reply.SocketIdentifier socketIdentifier = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier, pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier.Builder, pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifierOrBuilder> 
          getSocketIdentifierFieldBuilder() {
        if (socketIdentifierBuilder_ == null) {
          if (!(routingIdCase_ == 2)) {
            routingId_ = pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier.getDefaultInstance();
          }
          socketIdentifierBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier, pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier.Builder, pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifierOrBuilder>(
                  (pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier) routingId_,
                  getParentForChildren(),
                  isClean());
          routingId_ = null;
        }
        routingIdCase_ = 2;
        onChanged();
        return socketIdentifierBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:pt.uminho.di.a3m.sockets.request_reply.RoutingId)
    }

    // @@protoc_insertion_point(class_scope:pt.uminho.di.a3m.sockets.request_reply.RoutingId)
    private static final pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId();
    }

    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RoutingId>
        PARSER = new com.google.protobuf.AbstractParser<RoutingId>() {
      @java.lang.Override
      public RoutingId parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RoutingId> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RoutingId> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pt.uminho.di.a3m.sockets.request_reply.RequestReply.RoutingId getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SocketIdentifierOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pt.uminho.di.a3m.sockets.request_reply.SocketIdentifier)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string nodeId = 1;</code>
     * @return The nodeId.
     */
    java.lang.String getNodeId();
    /**
     * <code>string nodeId = 1;</code>
     * @return The bytes for nodeId.
     */
    com.google.protobuf.ByteString
        getNodeIdBytes();

    /**
     * <code>string tagId = 2;</code>
     * @return The tagId.
     */
    java.lang.String getTagId();
    /**
     * <code>string tagId = 2;</code>
     * @return The bytes for tagId.
     */
    com.google.protobuf.ByteString
        getTagIdBytes();
  }
  /**
   * Protobuf type {@code pt.uminho.di.a3m.sockets.request_reply.SocketIdentifier}
   */
  public static final class SocketIdentifier extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pt.uminho.di.a3m.sockets.request_reply.SocketIdentifier)
      SocketIdentifierOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 3,
        /* suffix= */ "",
        SocketIdentifier.class.getName());
    }
    // Use SocketIdentifier.newBuilder() to construct.
    private SocketIdentifier(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private SocketIdentifier() {
      nodeId_ = "";
      tagId_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pt.uminho.di.a3m.sockets.request_reply.RequestReply.internal_static_pt_uminho_di_a3m_sockets_request_reply_SocketIdentifier_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pt.uminho.di.a3m.sockets.request_reply.RequestReply.internal_static_pt_uminho_di_a3m_sockets_request_reply_SocketIdentifier_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier.class, pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier.Builder.class);
    }

    public static final int NODEID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object nodeId_ = "";
    /**
     * <code>string nodeId = 1;</code>
     * @return The nodeId.
     */
    @java.lang.Override
    public java.lang.String getNodeId() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nodeId_ = s;
        return s;
      }
    }
    /**
     * <code>string nodeId = 1;</code>
     * @return The bytes for nodeId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNodeIdBytes() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TAGID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object tagId_ = "";
    /**
     * <code>string tagId = 2;</code>
     * @return The tagId.
     */
    @java.lang.Override
    public java.lang.String getTagId() {
      java.lang.Object ref = tagId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tagId_ = s;
        return s;
      }
    }
    /**
     * <code>string tagId = 2;</code>
     * @return The bytes for tagId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTagIdBytes() {
      java.lang.Object ref = tagId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tagId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nodeId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, nodeId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tagId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, tagId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nodeId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, nodeId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tagId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, tagId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier)) {
        return super.equals(obj);
      }
      pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier other = (pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier) obj;

      if (!getNodeId()
          .equals(other.getNodeId())) return false;
      if (!getTagId()
          .equals(other.getTagId())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NODEID_FIELD_NUMBER;
      hash = (53 * hash) + getNodeId().hashCode();
      hash = (37 * hash) + TAGID_FIELD_NUMBER;
      hash = (53 * hash) + getTagId().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pt.uminho.di.a3m.sockets.request_reply.SocketIdentifier}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pt.uminho.di.a3m.sockets.request_reply.SocketIdentifier)
        pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifierOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pt.uminho.di.a3m.sockets.request_reply.RequestReply.internal_static_pt_uminho_di_a3m_sockets_request_reply_SocketIdentifier_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pt.uminho.di.a3m.sockets.request_reply.RequestReply.internal_static_pt_uminho_di_a3m_sockets_request_reply_SocketIdentifier_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier.class, pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier.Builder.class);
      }

      // Construct using pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        nodeId_ = "";
        tagId_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pt.uminho.di.a3m.sockets.request_reply.RequestReply.internal_static_pt_uminho_di_a3m_sockets_request_reply_SocketIdentifier_descriptor;
      }

      @java.lang.Override
      public pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier getDefaultInstanceForType() {
        return pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier.getDefaultInstance();
      }

      @java.lang.Override
      public pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier build() {
        pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier buildPartial() {
        pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier result = new pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.nodeId_ = nodeId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.tagId_ = tagId_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier) {
          return mergeFrom((pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier other) {
        if (other == pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier.getDefaultInstance()) return this;
        if (!other.getNodeId().isEmpty()) {
          nodeId_ = other.nodeId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getTagId().isEmpty()) {
          tagId_ = other.tagId_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                nodeId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                tagId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object nodeId_ = "";
      /**
       * <code>string nodeId = 1;</code>
       * @return The nodeId.
       */
      public java.lang.String getNodeId() {
        java.lang.Object ref = nodeId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nodeId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nodeId = 1;</code>
       * @return The bytes for nodeId.
       */
      public com.google.protobuf.ByteString
          getNodeIdBytes() {
        java.lang.Object ref = nodeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nodeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nodeId = 1;</code>
       * @param value The nodeId to set.
       * @return This builder for chaining.
       */
      public Builder setNodeId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        nodeId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string nodeId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNodeId() {
        nodeId_ = getDefaultInstance().getNodeId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string nodeId = 1;</code>
       * @param value The bytes for nodeId to set.
       * @return This builder for chaining.
       */
      public Builder setNodeIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        nodeId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object tagId_ = "";
      /**
       * <code>string tagId = 2;</code>
       * @return The tagId.
       */
      public java.lang.String getTagId() {
        java.lang.Object ref = tagId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tagId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tagId = 2;</code>
       * @return The bytes for tagId.
       */
      public com.google.protobuf.ByteString
          getTagIdBytes() {
        java.lang.Object ref = tagId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tagId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tagId = 2;</code>
       * @param value The tagId to set.
       * @return This builder for chaining.
       */
      public Builder setTagId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        tagId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string tagId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTagId() {
        tagId_ = getDefaultInstance().getTagId();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string tagId = 2;</code>
       * @param value The bytes for tagId to set.
       * @return This builder for chaining.
       */
      public Builder setTagIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        tagId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pt.uminho.di.a3m.sockets.request_reply.SocketIdentifier)
    }

    // @@protoc_insertion_point(class_scope:pt.uminho.di.a3m.sockets.request_reply.SocketIdentifier)
    private static final pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier();
    }

    public static pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SocketIdentifier>
        PARSER = new com.google.protobuf.AbstractParser<SocketIdentifier>() {
      @java.lang.Override
      public SocketIdentifier parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SocketIdentifier> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SocketIdentifier> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pt.uminho.di.a3m.sockets.request_reply.RequestReply.SocketIdentifier getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_uminho_di_a3m_sockets_request_reply_RRMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pt_uminho_di_a3m_sockets_request_reply_RRMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_uminho_di_a3m_sockets_request_reply_RoutingId_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pt_uminho_di_a3m_sockets_request_reply_RoutingId_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_uminho_di_a3m_sockets_request_reply_SocketIdentifier_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pt_uminho_di_a3m_sockets_request_reply_SocketIdentifier_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!src/main/proto/requestReply.proto\022&pt." +
      "uminho.di.a3m.sockets.request_reply\"_\n\005R" +
      "RMsg\022E\n\nroutingIds\030\001 \003(\01321.pt.uminho.di." +
      "a3m.sockets.request_reply.RoutingId\022\017\n\007p" +
      "ayload\030\002 \001(\014\"\207\001\n\tRoutingId\022\027\n\rintIdentif" +
      "ier\030\001 \001(\005H\000\022T\n\020socketIdentifier\030\002 \001(\01328." +
      "pt.uminho.di.a3m.sockets.request_reply.S" +
      "ocketIdentifierH\000B\013\n\troutingId\"1\n\020Socket" +
      "Identifier\022\016\n\006nodeId\030\001 \001(\t\022\r\n\005tagId\030\002 \001(" +
      "\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_pt_uminho_di_a3m_sockets_request_reply_RRMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pt_uminho_di_a3m_sockets_request_reply_RRMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pt_uminho_di_a3m_sockets_request_reply_RRMsg_descriptor,
        new java.lang.String[] { "RoutingIds", "Payload", });
    internal_static_pt_uminho_di_a3m_sockets_request_reply_RoutingId_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pt_uminho_di_a3m_sockets_request_reply_RoutingId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pt_uminho_di_a3m_sockets_request_reply_RoutingId_descriptor,
        new java.lang.String[] { "IntIdentifier", "SocketIdentifier", "RoutingId", });
    internal_static_pt_uminho_di_a3m_sockets_request_reply_SocketIdentifier_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_pt_uminho_di_a3m_sockets_request_reply_SocketIdentifier_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pt_uminho_di_a3m_sockets_request_reply_SocketIdentifier_descriptor,
        new java.lang.String[] { "NodeId", "TagId", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
