// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/proto/coreMessages.proto
// Protobuf Java Version: 4.27.3

package pt.uminho.di.a3m.core.messaging.payloads;

public final class CoreMessages {
  private CoreMessages() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 3,
      /* suffix= */ "",
      CoreMessages.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PValueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pt.uminho.di.a3m.core.messaging.PValue)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 int_value = 1;</code>
     * @return Whether the intValue field is set.
     */
    boolean hasIntValue();
    /**
     * <code>int32 int_value = 1;</code>
     * @return The intValue.
     */
    int getIntValue();

    /**
     * <code>float float_value = 2;</code>
     * @return Whether the floatValue field is set.
     */
    boolean hasFloatValue();
    /**
     * <code>float float_value = 2;</code>
     * @return The floatValue.
     */
    float getFloatValue();

    /**
     * <code>double double_value = 3;</code>
     * @return Whether the doubleValue field is set.
     */
    boolean hasDoubleValue();
    /**
     * <code>double double_value = 3;</code>
     * @return The doubleValue.
     */
    double getDoubleValue();

    /**
     * <pre>
     * To serialize complex objects, convert them to JSON
     * </pre>
     *
     * <code>string string_value = 4;</code>
     * @return Whether the stringValue field is set.
     */
    boolean hasStringValue();
    /**
     * <pre>
     * To serialize complex objects, convert them to JSON
     * </pre>
     *
     * <code>string string_value = 4;</code>
     * @return The stringValue.
     */
    java.lang.String getStringValue();
    /**
     * <pre>
     * To serialize complex objects, convert them to JSON
     * </pre>
     *
     * <code>string string_value = 4;</code>
     * @return The bytes for stringValue.
     */
    com.google.protobuf.ByteString
        getStringValueBytes();

    /**
     * <code>bool bool_value = 5;</code>
     * @return Whether the boolValue field is set.
     */
    boolean hasBoolValue();
    /**
     * <code>bool bool_value = 5;</code>
     * @return The boolValue.
     */
    boolean getBoolValue();

    CoreMessages.PValue.ValueCase getValueCase();
  }
  /**
   * <pre>
   * primitive value
   * </pre>
   *
   * Protobuf type {@code pt.uminho.di.a3m.core.messaging.PValue}
   */
  public static final class PValue extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pt.uminho.di.a3m.core.messaging.PValue)
      PValueOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 3,
        /* suffix= */ "",
        PValue.class.getName());
    }
    // Use PValue.newBuilder() to construct.
    private PValue(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PValue() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CoreMessages.internal_static_pt_uminho_di_a3m_core_messaging_PValue_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CoreMessages.internal_static_pt_uminho_di_a3m_core_messaging_PValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CoreMessages.PValue.class, CoreMessages.PValue.Builder.class);
    }

    private int valueCase_ = 0;
    @SuppressWarnings("serial")
    private java.lang.Object value_;
    public enum ValueCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      INT_VALUE(1),
      FLOAT_VALUE(2),
      DOUBLE_VALUE(3),
      STRING_VALUE(4),
      BOOL_VALUE(5),
      VALUE_NOT_SET(0);
      private final int value;
      private ValueCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ValueCase valueOf(int value) {
        return forNumber(value);
      }

      public static ValueCase forNumber(int value) {
        switch (value) {
          case 1: return INT_VALUE;
          case 2: return FLOAT_VALUE;
          case 3: return DOUBLE_VALUE;
          case 4: return STRING_VALUE;
          case 5: return BOOL_VALUE;
          case 0: return VALUE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ValueCase
    getValueCase() {
      return ValueCase.forNumber(
          valueCase_);
    }

    public static final int INT_VALUE_FIELD_NUMBER = 1;
    /**
     * <code>int32 int_value = 1;</code>
     * @return Whether the intValue field is set.
     */
    @java.lang.Override
    public boolean hasIntValue() {
      return valueCase_ == 1;
    }
    /**
     * <code>int32 int_value = 1;</code>
     * @return The intValue.
     */
    @java.lang.Override
    public int getIntValue() {
      if (valueCase_ == 1) {
        return (java.lang.Integer) value_;
      }
      return 0;
    }

    public static final int FLOAT_VALUE_FIELD_NUMBER = 2;
    /**
     * <code>float float_value = 2;</code>
     * @return Whether the floatValue field is set.
     */
    @java.lang.Override
    public boolean hasFloatValue() {
      return valueCase_ == 2;
    }
    /**
     * <code>float float_value = 2;</code>
     * @return The floatValue.
     */
    @java.lang.Override
    public float getFloatValue() {
      if (valueCase_ == 2) {
        return (java.lang.Float) value_;
      }
      return 0F;
    }

    public static final int DOUBLE_VALUE_FIELD_NUMBER = 3;
    /**
     * <code>double double_value = 3;</code>
     * @return Whether the doubleValue field is set.
     */
    @java.lang.Override
    public boolean hasDoubleValue() {
      return valueCase_ == 3;
    }
    /**
     * <code>double double_value = 3;</code>
     * @return The doubleValue.
     */
    @java.lang.Override
    public double getDoubleValue() {
      if (valueCase_ == 3) {
        return (java.lang.Double) value_;
      }
      return 0D;
    }

    public static final int STRING_VALUE_FIELD_NUMBER = 4;
    /**
     * <pre>
     * To serialize complex objects, convert them to JSON
     * </pre>
     *
     * <code>string string_value = 4;</code>
     * @return Whether the stringValue field is set.
     */
    public boolean hasStringValue() {
      return valueCase_ == 4;
    }
    /**
     * <pre>
     * To serialize complex objects, convert them to JSON
     * </pre>
     *
     * <code>string string_value = 4;</code>
     * @return The stringValue.
     */
    public java.lang.String getStringValue() {
      java.lang.Object ref = "";
      if (valueCase_ == 4) {
        ref = value_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (valueCase_ == 4) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * To serialize complex objects, convert them to JSON
     * </pre>
     *
     * <code>string string_value = 4;</code>
     * @return The bytes for stringValue.
     */
    public com.google.protobuf.ByteString
        getStringValueBytes() {
      java.lang.Object ref = "";
      if (valueCase_ == 4) {
        ref = value_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (valueCase_ == 4) {
          value_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BOOL_VALUE_FIELD_NUMBER = 5;
    /**
     * <code>bool bool_value = 5;</code>
     * @return Whether the boolValue field is set.
     */
    @java.lang.Override
    public boolean hasBoolValue() {
      return valueCase_ == 5;
    }
    /**
     * <code>bool bool_value = 5;</code>
     * @return The boolValue.
     */
    @java.lang.Override
    public boolean getBoolValue() {
      if (valueCase_ == 5) {
        return (java.lang.Boolean) value_;
      }
      return false;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (valueCase_ == 1) {
        output.writeInt32(
            1, (int)((java.lang.Integer) value_));
      }
      if (valueCase_ == 2) {
        output.writeFloat(
            2, (float)((java.lang.Float) value_));
      }
      if (valueCase_ == 3) {
        output.writeDouble(
            3, (double)((java.lang.Double) value_));
      }
      if (valueCase_ == 4) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, value_);
      }
      if (valueCase_ == 5) {
        output.writeBool(
            5, (boolean)((java.lang.Boolean) value_));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (valueCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(
              1, (int)((java.lang.Integer) value_));
      }
      if (valueCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(
              2, (float)((java.lang.Float) value_));
      }
      if (valueCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(
              3, (double)((java.lang.Double) value_));
      }
      if (valueCase_ == 4) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, value_);
      }
      if (valueCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(
              5, (boolean)((java.lang.Boolean) value_));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CoreMessages.PValue)) {
        return super.equals(obj);
      }
      CoreMessages.PValue other = (CoreMessages.PValue) obj;

      if (!getValueCase().equals(other.getValueCase())) return false;
      switch (valueCase_) {
        case 1:
          if (getIntValue()
              != other.getIntValue()) return false;
          break;
        case 2:
          if (java.lang.Float.floatToIntBits(getFloatValue())
              != java.lang.Float.floatToIntBits(
                  other.getFloatValue())) return false;
          break;
        case 3:
          if (java.lang.Double.doubleToLongBits(getDoubleValue())
              != java.lang.Double.doubleToLongBits(
                  other.getDoubleValue())) return false;
          break;
        case 4:
          if (!getStringValue()
              .equals(other.getStringValue())) return false;
          break;
        case 5:
          if (getBoolValue()
              != other.getBoolValue()) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (valueCase_) {
        case 1:
          hash = (37 * hash) + INT_VALUE_FIELD_NUMBER;
          hash = (53 * hash) + getIntValue();
          break;
        case 2:
          hash = (37 * hash) + FLOAT_VALUE_FIELD_NUMBER;
          hash = (53 * hash) + java.lang.Float.floatToIntBits(
              getFloatValue());
          break;
        case 3:
          hash = (37 * hash) + DOUBLE_VALUE_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              java.lang.Double.doubleToLongBits(getDoubleValue()));
          break;
        case 4:
          hash = (37 * hash) + STRING_VALUE_FIELD_NUMBER;
          hash = (53 * hash) + getStringValue().hashCode();
          break;
        case 5:
          hash = (37 * hash) + BOOL_VALUE_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
              getBoolValue());
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CoreMessages.PValue parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CoreMessages.PValue parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CoreMessages.PValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CoreMessages.PValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CoreMessages.PValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CoreMessages.PValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CoreMessages.PValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static CoreMessages.PValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static CoreMessages.PValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static CoreMessages.PValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CoreMessages.PValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static CoreMessages.PValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CoreMessages.PValue prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * primitive value
     * </pre>
     *
     * Protobuf type {@code pt.uminho.di.a3m.core.messaging.PValue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pt.uminho.di.a3m.core.messaging.PValue)
        CoreMessages.PValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CoreMessages.internal_static_pt_uminho_di_a3m_core_messaging_PValue_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CoreMessages.internal_static_pt_uminho_di_a3m_core_messaging_PValue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CoreMessages.PValue.class, CoreMessages.PValue.Builder.class);
      }

      // Construct using pt.uminho.di.a3m.core.messaging.CoreMessages.PValue.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        valueCase_ = 0;
        value_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CoreMessages.internal_static_pt_uminho_di_a3m_core_messaging_PValue_descriptor;
      }

      @java.lang.Override
      public CoreMessages.PValue getDefaultInstanceForType() {
        return CoreMessages.PValue.getDefaultInstance();
      }

      @java.lang.Override
      public CoreMessages.PValue build() {
        CoreMessages.PValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public CoreMessages.PValue buildPartial() {
        CoreMessages.PValue result = new CoreMessages.PValue(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(CoreMessages.PValue result) {
        int from_bitField0_ = bitField0_;
      }

      private void buildPartialOneofs(CoreMessages.PValue result) {
        result.valueCase_ = valueCase_;
        result.value_ = this.value_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CoreMessages.PValue) {
          return mergeFrom((CoreMessages.PValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CoreMessages.PValue other) {
        if (other == CoreMessages.PValue.getDefaultInstance()) return this;
        switch (other.getValueCase()) {
          case INT_VALUE: {
            setIntValue(other.getIntValue());
            break;
          }
          case FLOAT_VALUE: {
            setFloatValue(other.getFloatValue());
            break;
          }
          case DOUBLE_VALUE: {
            setDoubleValue(other.getDoubleValue());
            break;
          }
          case STRING_VALUE: {
            valueCase_ = 4;
            value_ = other.value_;
            onChanged();
            break;
          }
          case BOOL_VALUE: {
            setBoolValue(other.getBoolValue());
            break;
          }
          case VALUE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                value_ = input.readInt32();
                valueCase_ = 1;
                break;
              } // case 8
              case 21: {
                value_ = input.readFloat();
                valueCase_ = 2;
                break;
              } // case 21
              case 25: {
                value_ = input.readDouble();
                valueCase_ = 3;
                break;
              } // case 25
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();
                valueCase_ = 4;
                value_ = s;
                break;
              } // case 34
              case 40: {
                value_ = input.readBool();
                valueCase_ = 5;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int valueCase_ = 0;
      private java.lang.Object value_;
      public ValueCase
          getValueCase() {
        return ValueCase.forNumber(
            valueCase_);
      }

      public Builder clearValue() {
        valueCase_ = 0;
        value_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      /**
       * <code>int32 int_value = 1;</code>
       * @return Whether the intValue field is set.
       */
      public boolean hasIntValue() {
        return valueCase_ == 1;
      }
      /**
       * <code>int32 int_value = 1;</code>
       * @return The intValue.
       */
      public int getIntValue() {
        if (valueCase_ == 1) {
          return (java.lang.Integer) value_;
        }
        return 0;
      }
      /**
       * <code>int32 int_value = 1;</code>
       * @param value The intValue to set.
       * @return This builder for chaining.
       */
      public Builder setIntValue(int value) {

        valueCase_ = 1;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 int_value = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIntValue() {
        if (valueCase_ == 1) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>float float_value = 2;</code>
       * @return Whether the floatValue field is set.
       */
      public boolean hasFloatValue() {
        return valueCase_ == 2;
      }
      /**
       * <code>float float_value = 2;</code>
       * @return The floatValue.
       */
      public float getFloatValue() {
        if (valueCase_ == 2) {
          return (java.lang.Float) value_;
        }
        return 0F;
      }
      /**
       * <code>float float_value = 2;</code>
       * @param value The floatValue to set.
       * @return This builder for chaining.
       */
      public Builder setFloatValue(float value) {

        valueCase_ = 2;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float float_value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFloatValue() {
        if (valueCase_ == 2) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>double double_value = 3;</code>
       * @return Whether the doubleValue field is set.
       */
      public boolean hasDoubleValue() {
        return valueCase_ == 3;
      }
      /**
       * <code>double double_value = 3;</code>
       * @return The doubleValue.
       */
      public double getDoubleValue() {
        if (valueCase_ == 3) {
          return (java.lang.Double) value_;
        }
        return 0D;
      }
      /**
       * <code>double double_value = 3;</code>
       * @param value The doubleValue to set.
       * @return This builder for chaining.
       */
      public Builder setDoubleValue(double value) {

        valueCase_ = 3;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double double_value = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDoubleValue() {
        if (valueCase_ == 3) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <pre>
       * To serialize complex objects, convert them to JSON
       * </pre>
       *
       * <code>string string_value = 4;</code>
       * @return Whether the stringValue field is set.
       */
      @java.lang.Override
      public boolean hasStringValue() {
        return valueCase_ == 4;
      }
      /**
       * <pre>
       * To serialize complex objects, convert them to JSON
       * </pre>
       *
       * <code>string string_value = 4;</code>
       * @return The stringValue.
       */
      @java.lang.Override
      public java.lang.String getStringValue() {
        java.lang.Object ref = "";
        if (valueCase_ == 4) {
          ref = value_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (valueCase_ == 4) {
            value_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * To serialize complex objects, convert them to JSON
       * </pre>
       *
       * <code>string string_value = 4;</code>
       * @return The bytes for stringValue.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getStringValueBytes() {
        java.lang.Object ref = "";
        if (valueCase_ == 4) {
          ref = value_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (valueCase_ == 4) {
            value_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * To serialize complex objects, convert them to JSON
       * </pre>
       *
       * <code>string string_value = 4;</code>
       * @param value The stringValue to set.
       * @return This builder for chaining.
       */
      public Builder setStringValue(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        valueCase_ = 4;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * To serialize complex objects, convert them to JSON
       * </pre>
       *
       * <code>string string_value = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearStringValue() {
        if (valueCase_ == 4) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * To serialize complex objects, convert them to JSON
       * </pre>
       *
       * <code>string string_value = 4;</code>
       * @param value The bytes for stringValue to set.
       * @return This builder for chaining.
       */
      public Builder setStringValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        valueCase_ = 4;
        value_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>bool bool_value = 5;</code>
       * @return Whether the boolValue field is set.
       */
      public boolean hasBoolValue() {
        return valueCase_ == 5;
      }
      /**
       * <code>bool bool_value = 5;</code>
       * @return The boolValue.
       */
      public boolean getBoolValue() {
        if (valueCase_ == 5) {
          return (java.lang.Boolean) value_;
        }
        return false;
      }
      /**
       * <code>bool bool_value = 5;</code>
       * @param value The boolValue to set.
       * @return This builder for chaining.
       */
      public Builder setBoolValue(boolean value) {

        valueCase_ = 5;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool bool_value = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearBoolValue() {
        if (valueCase_ == 5) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pt.uminho.di.a3m.core.messaging.PValue)
    }

    // @@protoc_insertion_point(class_scope:pt.uminho.di.a3m.core.messaging.PValue)
    private static final CoreMessages.PValue DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CoreMessages.PValue();
    }

    public static CoreMessages.PValue getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PValue>
        PARSER = new com.google.protobuf.AbstractParser<PValue>() {
      @java.lang.Override
      public PValue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PValue> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PValue> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public CoreMessages.PValue getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PMapOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pt.uminho.di.a3m.core.messaging.PMap)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, .pt.uminho.di.a3m.core.messaging.PValue&gt; items = 1;</code>
     */
    int getItemsCount();
    /**
     * <code>map&lt;string, .pt.uminho.di.a3m.core.messaging.PValue&gt; items = 1;</code>
     */
    boolean containsItems(
        java.lang.String key);
    /**
     * Use {@link #getItemsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, CoreMessages.PValue>
    getItems();
    /**
     * <code>map&lt;string, .pt.uminho.di.a3m.core.messaging.PValue&gt; items = 1;</code>
     */
    java.util.Map<java.lang.String, CoreMessages.PValue>
    getItemsMap();
    /**
     * <code>map&lt;string, .pt.uminho.di.a3m.core.messaging.PValue&gt; items = 1;</code>
     */
    /* nullable */
CoreMessages.PValue getItemsOrDefault(
        java.lang.String key,
        /* nullable */
CoreMessages.PValue defaultValue);
    /**
     * <code>map&lt;string, .pt.uminho.di.a3m.core.messaging.PValue&gt; items = 1;</code>
     */
    CoreMessages.PValue getItemsOrThrow(
        java.lang.String key);
  }
  /**
   * <pre>
   * primitive map
   * </pre>
   *
   * Protobuf type {@code pt.uminho.di.a3m.core.messaging.PMap}
   */
  public static final class PMap extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pt.uminho.di.a3m.core.messaging.PMap)
      PMapOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 3,
        /* suffix= */ "",
        PMap.class.getName());
    }
    // Use PMap.newBuilder() to construct.
    private PMap(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PMap() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CoreMessages.internal_static_pt_uminho_di_a3m_core_messaging_PMap_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetItems();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CoreMessages.internal_static_pt_uminho_di_a3m_core_messaging_PMap_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CoreMessages.PMap.class, CoreMessages.PMap.Builder.class);
    }

    public static final int ITEMS_FIELD_NUMBER = 1;
    private static final class ItemsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, CoreMessages.PValue> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, CoreMessages.PValue>newDefaultInstance(
                  CoreMessages.internal_static_pt_uminho_di_a3m_core_messaging_PMap_ItemsEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  CoreMessages.PValue.getDefaultInstance());
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, CoreMessages.PValue> items_;
    private com.google.protobuf.MapField<java.lang.String, CoreMessages.PValue>
    internalGetItems() {
      if (items_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ItemsDefaultEntryHolder.defaultEntry);
      }
      return items_;
    }
    public int getItemsCount() {
      return internalGetItems().getMap().size();
    }
    /**
     * <code>map&lt;string, .pt.uminho.di.a3m.core.messaging.PValue&gt; items = 1;</code>
     */
    @java.lang.Override
    public boolean containsItems(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetItems().getMap().containsKey(key);
    }
    /**
     * Use {@link #getItemsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, CoreMessages.PValue> getItems() {
      return getItemsMap();
    }
    /**
     * <code>map&lt;string, .pt.uminho.di.a3m.core.messaging.PValue&gt; items = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, CoreMessages.PValue> getItemsMap() {
      return internalGetItems().getMap();
    }
    /**
     * <code>map&lt;string, .pt.uminho.di.a3m.core.messaging.PValue&gt; items = 1;</code>
     */
    @java.lang.Override
    public /* nullable */
CoreMessages.PValue getItemsOrDefault(
        java.lang.String key,
        /* nullable */
CoreMessages.PValue defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, CoreMessages.PValue> map =
          internalGetItems().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .pt.uminho.di.a3m.core.messaging.PValue&gt; items = 1;</code>
     */
    @java.lang.Override
    public CoreMessages.PValue getItemsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, CoreMessages.PValue> map =
          internalGetItems().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessage
        .serializeStringMapTo(
          output,
          internalGetItems(),
          ItemsDefaultEntryHolder.defaultEntry,
          1);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, CoreMessages.PValue> entry
           : internalGetItems().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, CoreMessages.PValue>
        items__ = ItemsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, items__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CoreMessages.PMap)) {
        return super.equals(obj);
      }
      CoreMessages.PMap other = (CoreMessages.PMap) obj;

      if (!internalGetItems().equals(
          other.internalGetItems())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetItems().getMap().isEmpty()) {
        hash = (37 * hash) + ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetItems().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CoreMessages.PMap parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CoreMessages.PMap parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CoreMessages.PMap parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CoreMessages.PMap parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CoreMessages.PMap parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CoreMessages.PMap parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CoreMessages.PMap parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static CoreMessages.PMap parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static CoreMessages.PMap parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static CoreMessages.PMap parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CoreMessages.PMap parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static CoreMessages.PMap parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CoreMessages.PMap prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * primitive map
     * </pre>
     *
     * Protobuf type {@code pt.uminho.di.a3m.core.messaging.PMap}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pt.uminho.di.a3m.core.messaging.PMap)
        CoreMessages.PMapOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CoreMessages.internal_static_pt_uminho_di_a3m_core_messaging_PMap_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
          int number) {
        switch (number) {
          case 1:
            return internalGetItems();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableItems();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CoreMessages.internal_static_pt_uminho_di_a3m_core_messaging_PMap_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CoreMessages.PMap.class, CoreMessages.PMap.Builder.class);
      }

      // Construct using pt.uminho.di.a3m.core.messaging.CoreMessages.PMap.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        internalGetMutableItems().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CoreMessages.internal_static_pt_uminho_di_a3m_core_messaging_PMap_descriptor;
      }

      @java.lang.Override
      public CoreMessages.PMap getDefaultInstanceForType() {
        return CoreMessages.PMap.getDefaultInstance();
      }

      @java.lang.Override
      public CoreMessages.PMap build() {
        CoreMessages.PMap result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public CoreMessages.PMap buildPartial() {
        CoreMessages.PMap result = new CoreMessages.PMap(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(CoreMessages.PMap result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.items_ = internalGetItems().build(ItemsDefaultEntryHolder.defaultEntry);
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CoreMessages.PMap) {
          return mergeFrom((CoreMessages.PMap)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CoreMessages.PMap other) {
        if (other == CoreMessages.PMap.getDefaultInstance()) return this;
        internalGetMutableItems().mergeFrom(
            other.internalGetItems());
        bitField0_ |= 0x00000001;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.MapEntry<java.lang.String, CoreMessages.PValue>
                items__ = input.readMessage(
                    ItemsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableItems().ensureBuilderMap().put(
                    items__.getKey(), items__.getValue());
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private static final class ItemsConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, CoreMessages.PValueOrBuilder, CoreMessages.PValue> {
        @java.lang.Override
        public CoreMessages.PValue build(CoreMessages.PValueOrBuilder val) {
          if (val instanceof CoreMessages.PValue) { return (CoreMessages.PValue) val; }
          return ((CoreMessages.PValue.Builder) val).build();
        }

        @java.lang.Override
        public com.google.protobuf.MapEntry<java.lang.String, CoreMessages.PValue> defaultEntry() {
          return ItemsDefaultEntryHolder.defaultEntry;
        }
      };
      private static final ItemsConverter itemsConverter = new ItemsConverter();

      private com.google.protobuf.MapFieldBuilder<
          java.lang.String, CoreMessages.PValueOrBuilder, CoreMessages.PValue, CoreMessages.PValue.Builder> items_;
      private com.google.protobuf.MapFieldBuilder<java.lang.String, CoreMessages.PValueOrBuilder, CoreMessages.PValue, CoreMessages.PValue.Builder>
          internalGetItems() {
        if (items_ == null) {
          return new com.google.protobuf.MapFieldBuilder<>(itemsConverter);
        }
        return items_;
      }
      private com.google.protobuf.MapFieldBuilder<java.lang.String, CoreMessages.PValueOrBuilder, CoreMessages.PValue, CoreMessages.PValue.Builder>
          internalGetMutableItems() {
        if (items_ == null) {
          items_ = new com.google.protobuf.MapFieldBuilder<>(itemsConverter);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return items_;
      }
      public int getItemsCount() {
        return internalGetItems().ensureBuilderMap().size();
      }
      /**
       * <code>map&lt;string, .pt.uminho.di.a3m.core.messaging.PValue&gt; items = 1;</code>
       */
      @java.lang.Override
      public boolean containsItems(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetItems().ensureBuilderMap().containsKey(key);
      }
      /**
       * Use {@link #getItemsMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, CoreMessages.PValue> getItems() {
        return getItemsMap();
      }
      /**
       * <code>map&lt;string, .pt.uminho.di.a3m.core.messaging.PValue&gt; items = 1;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, CoreMessages.PValue> getItemsMap() {
        return internalGetItems().getImmutableMap();
      }
      /**
       * <code>map&lt;string, .pt.uminho.di.a3m.core.messaging.PValue&gt; items = 1;</code>
       */
      @java.lang.Override
      public /* nullable */
CoreMessages.PValue getItemsOrDefault(
          java.lang.String key,
          /* nullable */
CoreMessages.PValue defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, CoreMessages.PValueOrBuilder> map = internalGetMutableItems().ensureBuilderMap();
        return map.containsKey(key) ? itemsConverter.build(map.get(key)) : defaultValue;
      }
      /**
       * <code>map&lt;string, .pt.uminho.di.a3m.core.messaging.PValue&gt; items = 1;</code>
       */
      @java.lang.Override
      public CoreMessages.PValue getItemsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, CoreMessages.PValueOrBuilder> map = internalGetMutableItems().ensureBuilderMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return itemsConverter.build(map.get(key));
      }
      public Builder clearItems() {
        bitField0_ = (bitField0_ & ~0x00000001);
        internalGetMutableItems().clear();
        return this;
      }
      /**
       * <code>map&lt;string, .pt.uminho.di.a3m.core.messaging.PValue&gt; items = 1;</code>
       */
      public Builder removeItems(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableItems().ensureBuilderMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, CoreMessages.PValue>
          getMutableItems() {
        bitField0_ |= 0x00000001;
        return internalGetMutableItems().ensureMessageMap();
      }
      /**
       * <code>map&lt;string, .pt.uminho.di.a3m.core.messaging.PValue&gt; items = 1;</code>
       */
      public Builder putItems(
          java.lang.String key,
          CoreMessages.PValue value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableItems().ensureBuilderMap()
            .put(key, value);
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>map&lt;string, .pt.uminho.di.a3m.core.messaging.PValue&gt; items = 1;</code>
       */
      public Builder putAllItems(
          java.util.Map<java.lang.String, CoreMessages.PValue> values) {
        for (java.util.Map.Entry<java.lang.String, CoreMessages.PValue> e : values.entrySet()) {
          if (e.getKey() == null || e.getValue() == null) {
            throw new NullPointerException();
          }
        }
        internalGetMutableItems().ensureBuilderMap()
            .putAll(values);
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>map&lt;string, .pt.uminho.di.a3m.core.messaging.PValue&gt; items = 1;</code>
       */
      public CoreMessages.PValue.Builder putItemsBuilderIfAbsent(
          java.lang.String key) {
        java.util.Map<java.lang.String, CoreMessages.PValueOrBuilder> builderMap = internalGetMutableItems().ensureBuilderMap();
        CoreMessages.PValueOrBuilder entry = builderMap.get(key);
        if (entry == null) {
          entry = CoreMessages.PValue.newBuilder();
          builderMap.put(key, entry);
        }
        if (entry instanceof CoreMessages.PValue) {
          entry = ((CoreMessages.PValue) entry).toBuilder();
          builderMap.put(key, entry);
        }
        return (CoreMessages.PValue.Builder) entry;
      }

      // @@protoc_insertion_point(builder_scope:pt.uminho.di.a3m.core.messaging.PMap)
    }

    // @@protoc_insertion_point(class_scope:pt.uminho.di.a3m.core.messaging.PMap)
    private static final CoreMessages.PMap DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CoreMessages.PMap();
    }

    public static CoreMessages.PMap getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PMap>
        PARSER = new com.google.protobuf.AbstractParser<PMap>() {
      @java.lang.Override
      public PMap parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PMap> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PMap> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public CoreMessages.PMap getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ErrorPayloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pt.uminho.di.a3m.core.messaging.ErrorPayload)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes code = 1;</code>
     * @return The code.
     */
    com.google.protobuf.ByteString getCode();

    /**
     * <code>string text = 2;</code>
     * @return The text.
     */
    java.lang.String getText();
    /**
     * <code>string text = 2;</code>
     * @return The bytes for text.
     */
    com.google.protobuf.ByteString
        getTextBytes();
  }
  /**
   * <pre>
   * error payload
   * </pre>
   *
   * Protobuf type {@code pt.uminho.di.a3m.core.messaging.ErrorPayload}
   */
  public static final class ErrorPayload extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pt.uminho.di.a3m.core.messaging.ErrorPayload)
      ErrorPayloadOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 3,
        /* suffix= */ "",
        ErrorPayload.class.getName());
    }
    // Use ErrorPayload.newBuilder() to construct.
    private ErrorPayload(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ErrorPayload() {
      code_ = com.google.protobuf.ByteString.EMPTY;
      text_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CoreMessages.internal_static_pt_uminho_di_a3m_core_messaging_ErrorPayload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CoreMessages.internal_static_pt_uminho_di_a3m_core_messaging_ErrorPayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CoreMessages.ErrorPayload.class, CoreMessages.ErrorPayload.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString code_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes code = 1;</code>
     * @return The code.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getCode() {
      return code_;
    }

    public static final int TEXT_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object text_ = "";
    /**
     * <code>string text = 2;</code>
     * @return The text.
     */
    @java.lang.Override
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      }
    }
    /**
     * <code>string text = 2;</code>
     * @return The bytes for text.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!code_.isEmpty()) {
        output.writeBytes(1, code_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(text_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, text_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!code_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, code_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(text_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, text_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CoreMessages.ErrorPayload)) {
        return super.equals(obj);
      }
      CoreMessages.ErrorPayload other = (CoreMessages.ErrorPayload) obj;

      if (!getCode()
          .equals(other.getCode())) return false;
      if (!getText()
          .equals(other.getText())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode().hashCode();
      hash = (37 * hash) + TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getText().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CoreMessages.ErrorPayload parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CoreMessages.ErrorPayload parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CoreMessages.ErrorPayload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CoreMessages.ErrorPayload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CoreMessages.ErrorPayload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CoreMessages.ErrorPayload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CoreMessages.ErrorPayload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static CoreMessages.ErrorPayload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static CoreMessages.ErrorPayload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static CoreMessages.ErrorPayload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CoreMessages.ErrorPayload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static CoreMessages.ErrorPayload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CoreMessages.ErrorPayload prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * error payload
     * </pre>
     *
     * Protobuf type {@code pt.uminho.di.a3m.core.messaging.ErrorPayload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pt.uminho.di.a3m.core.messaging.ErrorPayload)
        CoreMessages.ErrorPayloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CoreMessages.internal_static_pt_uminho_di_a3m_core_messaging_ErrorPayload_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CoreMessages.internal_static_pt_uminho_di_a3m_core_messaging_ErrorPayload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CoreMessages.ErrorPayload.class, CoreMessages.ErrorPayload.Builder.class);
      }

      // Construct using pt.uminho.di.a3m.core.messaging.CoreMessages.ErrorPayload.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        code_ = com.google.protobuf.ByteString.EMPTY;
        text_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CoreMessages.internal_static_pt_uminho_di_a3m_core_messaging_ErrorPayload_descriptor;
      }

      @java.lang.Override
      public CoreMessages.ErrorPayload getDefaultInstanceForType() {
        return CoreMessages.ErrorPayload.getDefaultInstance();
      }

      @java.lang.Override
      public CoreMessages.ErrorPayload build() {
        CoreMessages.ErrorPayload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public CoreMessages.ErrorPayload buildPartial() {
        CoreMessages.ErrorPayload result = new CoreMessages.ErrorPayload(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(CoreMessages.ErrorPayload result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.code_ = code_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.text_ = text_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CoreMessages.ErrorPayload) {
          return mergeFrom((CoreMessages.ErrorPayload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CoreMessages.ErrorPayload other) {
        if (other == CoreMessages.ErrorPayload.getDefaultInstance()) return this;
        if (other.getCode() != com.google.protobuf.ByteString.EMPTY) {
          setCode(other.getCode());
        }
        if (!other.getText().isEmpty()) {
          text_ = other.text_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                code_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                text_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString code_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes code = 1;</code>
       * @return The code.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getCode() {
        return code_;
      }
      /**
       * <code>bytes code = 1;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        code_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bytes code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = getDefaultInstance().getCode();
        onChanged();
        return this;
      }

      private java.lang.Object text_ = "";
      /**
       * <code>string text = 2;</code>
       * @return The text.
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string text = 2;</code>
       * @return The bytes for text.
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string text = 2;</code>
       * @param value The text to set.
       * @return This builder for chaining.
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        text_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string text = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearText() {
        text_ = getDefaultInstance().getText();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string text = 2;</code>
       * @param value The bytes for text to set.
       * @return This builder for chaining.
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        text_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pt.uminho.di.a3m.core.messaging.ErrorPayload)
    }

    // @@protoc_insertion_point(class_scope:pt.uminho.di.a3m.core.messaging.ErrorPayload)
    private static final CoreMessages.ErrorPayload DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CoreMessages.ErrorPayload();
    }

    public static CoreMessages.ErrorPayload getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ErrorPayload>
        PARSER = new com.google.protobuf.AbstractParser<ErrorPayload>() {
      @java.lang.Override
      public ErrorPayload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ErrorPayload> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ErrorPayload> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public CoreMessages.ErrorPayload getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_uminho_di_a3m_core_messaging_PValue_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pt_uminho_di_a3m_core_messaging_PValue_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_uminho_di_a3m_core_messaging_PMap_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pt_uminho_di_a3m_core_messaging_PMap_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_uminho_di_a3m_core_messaging_PMap_ItemsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pt_uminho_di_a3m_core_messaging_PMap_ItemsEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_uminho_di_a3m_core_messaging_ErrorPayload_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pt_uminho_di_a3m_core_messaging_ErrorPayload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!src/main/proto/coreMessages.proto\022\037pt." +
      "uminho.di.a3m.core.messaging\"\203\001\n\006PValue\022" +
      "\023\n\tint_value\030\001 \001(\005H\000\022\025\n\013float_value\030\002 \001(" +
      "\002H\000\022\026\n\014double_value\030\003 \001(\001H\000\022\026\n\014string_va" +
      "lue\030\004 \001(\tH\000\022\024\n\nbool_value\030\005 \001(\010H\000B\007\n\005val" +
      "ue\"\236\001\n\004PMap\022?\n\005items\030\001 \003(\01320.pt.uminho.d" +
      "i.a3m.core.messaging.PMap.ItemsEntry\032U\n\n" +
      "ItemsEntry\022\013\n\003key\030\001 \001(\t\0226\n\005value\030\002 \001(\0132\'" +
      ".pt.uminho.di.a3m.core.messaging.PValue:" +
      "\0028\001\"*\n\014ErrorPayload\022\014\n\004code\030\001 \001(\014\022\014\n\004tex" +
      "t\030\002 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_pt_uminho_di_a3m_core_messaging_PValue_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pt_uminho_di_a3m_core_messaging_PValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pt_uminho_di_a3m_core_messaging_PValue_descriptor,
        new java.lang.String[] { "IntValue", "FloatValue", "DoubleValue", "StringValue", "BoolValue", "Value", });
    internal_static_pt_uminho_di_a3m_core_messaging_PMap_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pt_uminho_di_a3m_core_messaging_PMap_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pt_uminho_di_a3m_core_messaging_PMap_descriptor,
        new java.lang.String[] { "Items", });
    internal_static_pt_uminho_di_a3m_core_messaging_PMap_ItemsEntry_descriptor =
      internal_static_pt_uminho_di_a3m_core_messaging_PMap_descriptor.getNestedTypes().get(0);
    internal_static_pt_uminho_di_a3m_core_messaging_PMap_ItemsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pt_uminho_di_a3m_core_messaging_PMap_ItemsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_pt_uminho_di_a3m_core_messaging_ErrorPayload_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_pt_uminho_di_a3m_core_messaging_ErrorPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pt_uminho_di_a3m_core_messaging_ErrorPayload_descriptor,
        new java.lang.String[] { "Code", "Text", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
